routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Model\Item;
use App\Model\Merchant;

Route::get('/test', function () {
    $feed = \Storage::get('1');
    $feed = json_decode($feed, true);
    $products = $feed['products'];
    foreach ($products as $product) {
        dump($product['images'][0]);
//        foreach ($product['price'] as $price) {
//            $price = json_decode($price,true);
//            dump($price['amount']);
//        }
    }
});
//Route::get('/', 'IndexController@home')->name('home');
Route::get('/', 'IndexController@index')->name('index');
//Route::get('/item/{merchant}/{item}/{slug_title}', 'IndexController@show')->name('show');
Route::get('/item/{slug_title}', 'IndexController@show')->name('show');
Route::post('/', 'IndexController@mySearch');

Route::get('/about', 'IndexController@about');


Route::get('/privacy-policy', 'IndexController@privacy');


//toont alle merken`
Route::get('/brands', 'IndexController@brands')->name('brands');
Route::get('/brand/{brand}', 'IndexController@productByBrand')->name('brand');

//toon alle merchants
Route::get('/merchants', 'IndexController@merchantsView')->name('merchants');
Route::get('/merchant/{merchant}', 'IndexController@itemsByMerchant')->name('items');

Route::group(['prefix' => '/weflycheap', 'as' => 'weflycheap.'], function () {
    Route::group(['prefix' => '/merchants', 'as' => 'merchants.'], function () {
        //fetches all merchants
        Route::get('/', 'MerchantsController@index')->name('index');
        //stores new merchant
        Route::post('/{merchant?}', 'MerchantsController@store')->name('store');
        //creates the form/view to create a merchant
        Route::get('/create', 'MerchantsController@create')->name('create');
        //Renders a form then fetches the current merchant
        Route::get('/edit/{merchant}', 'MerchantsController@edit')->name('edit');
        //Deletes the current merchant
        Route::delete('/delete/{merchant}', 'MerchantsController@destroy')->name('destroy');

    });
});

Route::get('/duplicates/{item}', 'IndexController@duplicate')->name('duplicates');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/MerchantsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MerchantSaveRequest;
use App\Model\Merchant;
use Illuminate\Http\Request;

class MerchantsController extends Controller
{
    // shows a list of merchants GET
    public function index()
    {
        $merchants = Merchant::all();
        return view('merchants.all', compact('merchants'));
    }

    // shows a form to create a merchant GET
    public function create(Merchant $merchant)
    {
        return view('merchants.create', compact('merchant'));
    }

    // stores the data we received from the create form POST
    // or updates a merchant with the new data we received from the edit form POST
    public function store(MerchantSaveRequest $request, Merchant $merchant)
    {
        if ($merchant->exists) {
            $merchant->update($request->all());
            \Session::flash('message', 'Merchant update');
            \Session::flash('alert-class', 'alert alert-success');
        } else {
            $merchant = Merchant::create($request->all());
            \Session::flash('message', 'New Merchant Created');
            \Session::flash('alert-class', 'alert alert-success');
            //WORDT GEBRUIKT ALS TEST VOOR MEZELF
        }


        return redirect()->route('weflycheap.merchants.index');
    }

    // returns a form pre-filled with a merchants data... so that we can edit this merchant GET
    public function edit(MerchantSaveRequest $request, Merchant $merchant)
    {
        return view('merchants.edit', compact('merchant'));
    }

    //delete the current merchant
    public function destroy(MerchantSaveRequest $request, Merchant $merchant)
    {
        $merchant->delete();
        return response()->json(['success' => 'RECORD HAS BEEN DELETED']);
    }
}

resources/views/merchants/all.blade.php
@extends('layouts.admin_layout')
@section('admin_content')
    <div class="fresh-table full-color-azure full-screen-table" id="fresh-table">
        <div class="row">
            <ul class="text-center col-xs-6">
                <a class="btn btn-facebook" href="{{url('weflycheap/merchants/create')}}">ADD MERCHANTS</a>
            </ul>
            <h2 class="header text-center col-xs-6">
                We Fly Cheap
            </h2>
        </div>
        @if(Session::has('message'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
        @endif

        <table id="fresh-table" class="table table-bordered table-responsive-lg">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Logo</th>
                <th scope="col">Website</th>
                <th scope="col">Feed_xml</th>
                <th scope="col">Active</th>
                <th scope="col" data-field="active" data-sortable="true">Actions</th>
            </tr>
            </thead>
            <tbody>


            @if($merchants)

                @foreach($merchants as $merchant)

                    <tr>
                        <td>{{$merchant->id}}</td>
                        <td>
                            <a href="{{route('items',$merchant->id)}}">
                            {{$merchant->name}}
                            </a></td>
                        <td>{{$merchant->description}}</td>
                        <td><img class="image-logo" src="{{$merchant->logo}}" alt=""></td>
                        <td><a href="{{$merchant->website}}">{{$merchant->website}}</a></td>
                        <td>{{$merchant->feed_xml}}</td>
                        <td>
                            @if ($merchant->active === 1)
                                Active
                            @endif
                            @if($merchant->active === 0)
                                Inactive
                            @endif
                        </td>
                        <td>
                            <a href="{{ route ('weflycheap.merchants.edit',$merchant->id) }}"
                               data-target="#deleteUserConfirmation"
                               class="btn btn-success">Bewerken</a>

                            <button class="deleteProduct btn btn-danger" data-id="{{$merchant->id}}"
                                    data-token="{{ csrf_token() }}">Verwijderen
                            </button>

                        </td>
                    </tr>
                @endforeach
            @endif()
            </tbody>
        </table>
    </div>
@stop


@section('scripts')
    @parent
    <script>
        $(".deleteProduct").click(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token]').attr('content')
                }
            });
            var id = $(this).data("id");
            $.ajax(
                {
                    url: "{!! url('smartbeheer/merchants/delete') !!}" + "/" + id,
                    type: 'DELETE',
                    dataType: "JSON",
                    data: {
                        '_token': $('meta[name=csrf-token]').attr("content"),
                    },
                    success: function (response) {
                        confirm('Are you sure?');
                    },
                    error: function (xhr) {
                    }
                });
            location.reload();
        });
    </script>
@stop

<style>
    .image-logo {
        width: 50px;
    }

    .image-logo:hover {
        width: 150px;
        opacity: 1;
        transform: scale(1.0, 1.5);
    }
</style>

resources/views/merchants/create.blade.php
@extends('layouts.admin_layout')

@section('admin_forms_content')
    

<div class="container">
    <h1>{{$merchant->name}}</h1>
    <form method="POST" action="{!! route('weflycheap.merchants.store', ['merchant' => $merchant]) !!}">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Merchants name</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter the merchants name"
                       value="">
            </div>
        </div>

        <div class="form-group">
            <label for="description" class="cols-sm-2 control-label">Description</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="description" id="description"
                       placeholder="Enter a description about the merchant">
            </div>
        </div>

        <div class="form-group">
            <label for="logo" class="cols-sm-2 control-label">Upload a Logo</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="logo" id="logo" placeholder="CLick here to upload a logo">
            </div>
        </div>

        <div class="form-group">
            <label for="website" class="cols-sm-2 control-label">Enter a website for the merchant</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="website" id="website"
                       placeholder="Enter the merchants website">
            </div>
        </div>

        <div class="form-group">
            <label for="xml" class="cols-sm-2 control-label">Enter xml url for the merchant</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="feed_xml" id="xml"
                       placeholder="Enter xml url for the merchant">
            </div>
        </div>

        <div class="form-group float-right">
            <label for="logo" class="cols-sm-2 control-label">Enable the merchant</label>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <select name="active" id="active" class="form-control">
                    <option value="0">Disable Merchant</option>
                    <option value="1">Enable Merchant</option>
                </select>
            </div>
        </div>

        <div class="form-group ">
            <input type="submit" name="submit" id="button" class="btn btn-primary btn-lg btn-block login-button">
        </div>


    </form>
</div>
@stop

resources/views/merchants/edit.blade.php
@extends('layouts.admin_layout')
@section('admin_forms_content')
    <div class="container">
        <h5>Edit Merchant</h5>
        <h1>{{request()->route('id')}}</h1>
        <form method="POST"
              action="{!! route('smartbeheer.merchants.store', ['merchant' => $merchant->id]) !!}">
            {{csrf_field()}}
            <div class="form-group">
                <label for="name" class="cols-sm-2 control-label">Merchants name</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="name" id="name"
                           placeholder="Enter the merchants name" value="{{$merchant->name}}">
                </div>
            </div>

            <div class="form-group">
                <label for="description" class="cols-sm-2 control-label">Description</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="description" id="description"
                           placeholder="Enter a description about the merchant"
                           value="{{$merchant->description}}">
                </div>
            </div>

            <div class="form-group">
                <label for="logo" class="cols-sm-2 control-label">Upload a Logo</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="logo" id="logo"
                           placeholder="CLick here to upload a logo" value="{{$merchant->logo}}">
                </div>
            </div>

            <div class="form-group">
                <label for="website" class="cols-sm-2 control-label">Enter a website for the merchant</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="website" id="website"
                           placeholder="Enter the merchants website" value="{{$merchant->website}}">
                </div>
            </div>

            <div class="form-group">
                <label for="xml" class="cols-sm-2 control-label">Enter xml url for the merchant</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="feed_xml" id="xml"
                           placeholder="Enter xml url for the merchant" value="{{$merchant->feed_xml}}">
                </div>
            </div>

            <div class="form-group">
                <label for="logo" class="cols-sm-2 control-label">Enable the merchant</label>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <select name="active" id="active" class="form-control">
                        <option value="0">Disable Merchant</option>
                        <option value="1">Enable Merchant</option>
                    </select>
                </div>
            </div>

            <div class="form-group ">
                <input type="submit" name="submit" id="button"
                       class="btn btn-success btn-lg btn-block login-button">
            </div>


        </form>
    </div>
@stop

resources/views/merchants/test.blade.php
<script type="text/javascript">
    $(document).ready(function() {
        $('#student_table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": "{{ route('ajaxdata.getdata') }}",
            "columns":[
                { "data": "first_name" },
                { "data": "last_name" },
                { "data": "action", orderable:false, searchable: false},
                { "data":"checkbox", orderable:false, searchable:false}
            ]
        });

        $('#add_data').click(function(){
            $('#studentModal').modal('show');
            $('#student_form')[0].reset();
            $('#form_output').html('');
            $('#button_action').val('insert');
            $('#action').val('Add');
            $('.modal-title').text('Add Data');
        });

        $('#student_form').on('submit', function(event){
            event.preventDefault();
            var form_data = $(this).serialize();
            $.ajax({
                url:"{{ route('ajaxdata.postdata') }}",
                method:"POST",
                data:form_data,
                dataType:"json",
                success:function(data)
                {
                    if(data.error.length > 0)
                    {
                        var error_html = '';
                        for(var count = 0; count < data.error.length; count++)
                        {
                            error_html += '<div class="alert alert-danger">'+data.error[count]+'</div>';
                        }
                        $('#form_output').html(error_html);
                    }
                    else
                    {
                        $('#form_output').html(data.success);
                        $('#student_form')[0].reset();
                        $('#action').val('Add');
                        $('.modal-title').text('Add Data');
                        $('#button_action').val('insert');
                        $('#student_table').DataTable().ajax.reload();
                    }
                }
            })
        });

        $(document).on('click', '.edit', function(){
            var id = $(this).attr("id");
            $('#form_output').html('');
            $.ajax({
                url:"{{route('ajaxdata.fetchdata')}}",
                method:'get',
                data:{id:id},
                dataType:'json',
                success:function(data)
                {
                    $('#first_name').val(data.first_name);
                    $('#last_name').val(data.last_name);
                    $('#student_id').val(id);
                    $('#studentModal').modal('show');
                    $('#action').val('Edit');
                    $('.modal-title').text('Edit Data');
                    $('#button_action').val('update');
                }
            })
        });

        $(document).on('click', '.delete', function(){
            var id = $(this).attr('id');
            if(confirm("Are you sure you want to Delete this data?"))
            {
                $.ajax({
                    url:"{{route('ajaxdata.removedata')}}",
                    mehtod:"get",
                    data:{id:id},
                    success:function(data)
                    {
                        alert(data);
                        $('#student_table').DataTable().ajax.reload();
                        $('#student_table').DataTable().ajax.reload();
                    }
                })
            }
            else
            {
                return false;
            }
        });

        $(document).on('click', '#bulk_delete', function(){
            var id = [];
            if(confirm("Are you sure you want to Delete this data?"))
            {
                $('.student_checkbox:checked').each(function(){
                    id.push($(this).val());
                });
                if(id.length > 0)
                {
                    $.ajax({
                        url:"{{ route('ajaxdata.massremove')}}",
                        method:"get",
                        data:{id:id},
                        success:function(data)
                        {
                            alert(data);
                            $('#student_table').DataTable().ajax.reload();
                        }
                    });
                }
                else
                {
                    alert("Please select atleast one checkbox");
                }
            }
        });

    });
</script>